uploads = []

[[generated]]
id = "mjJpb1upi8BsYK1eEd6lX"
uri = "file://artifacts/panel-trenera-mobile/assets/images/icon.png"
type = "image"
title = "panel trenera app icon"

[[generated]]
id = "Ww4Vbx0ZtubwNcmYoUwU7"
uri = "file://artifacts/panel-trenera-mobile/assets/images/adaptive-icon.png"
type = "image"
title = "adaptive icon foreground"

[[outputs]]
id = "uE-fex3CeCaTEeJUOx1u_"
uri = "file://paneltrenera-keystore.zip"
type = "unspecified"
title = "Pobierz keystore Android"
