uploads = []

[[generated]]
id = "Ww4Vbx0ZtubwNcmYoUwU7"
uri = "file://artifacts/panel-trenera-mobile/assets/images/adaptive-icon.png"
type = "image"
title = "adaptive icon foreground"

[[outputs]]
id = "uE-fex3CeCaTEeJUOx1u_"
uri = "file://paneltrenera-keystore.zip"
type = "unspecified"
title = "Pobierz keystore Android"

[[outputs]]
id = "6LZmUr6iU4J28PAASei7W"
uri = "file://ios-fixes.zip"
type = "unspecified"
title = "iOS fixes — 4 pliki"
